from __future__ import annotations
from dataclasses import dataclass
from pathlib import Path


import argparse
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


@dataclass(frozen=True)
class CountryQueryConfig:
    country_label: str
    district_locations: list[str]
    focus_locations: list[str]
    province_locations: list[str]
    air_ticket_locations: list[str]


COUNTRY_CONFIGS: dict[str, CountryQueryConfig] = {
    "thailand": CountryQueryConfig(
        country_label="Thailand",
        district_locations=[
            "Sukhumvit Bangkok",
            "Silom Bangkok",
            "Sathorn Bangkok",
            "Khao San Bangkok",
            "Siam Bangkok",
            "Ratchadaphisek Bangkok",
            "Bang Rak Bangkok",
            "Chatuchak Bangkok",
            "Pratunam Bangkok",
            "Thonburi Bangkok",
            "Dusit Bangkok",
            "Huai Khwang Bangkok",
            "Lat Phrao Bangkok",
            "Bang Kapi Bangkok",
            "Phra Nakhon Bangkok",
            "Khlong Toei Bangkok",
            "Din Daeng Bangkok",
            "Phaya Thai Bangkok",
            "Watthana Bangkok",
            "Bang Na Bangkok",
            "Bangkapi Bangkok",
            "Don Mueang Bangkok",
            "Lak Si Bangkok",
            "Min Buri Bangkok",
            "Nong Khaem Bangkok",
            "Chiang Mai Old City",
            "Chiang Mai Nimmanhaemin",
            "Chiang Mai Night Bazaar area",
            "Phuket Town",
            "Patong Phuket",
            "Kata Phuket",
            "Karon Phuket",
            "North Pattaya",
            "South Pattaya",
            "Jomtien Pattaya",
            "Krabi Town",
            "Ao Nang Krabi",
        ],
        focus_locations=[
            "Bangkok",
            "Chiang Mai",
            "Phuket",
            "Pattaya",
            "Krabi",
            "Koh Samui",
            "Surat Thani",
            "Chiang Rai",
            "Hua Hin",
            "Pai",
            "Koh Phangan",
            "Koh Tao",
            "Koh Lanta",
            "Koh Chang",
            "Koh Lipe",
        ],
        province_locations=[
            "Lampang",
            "Lamphun",
            "Mae Hong Son",
            "Nan",
            "Phrae",
            "Phayao",
            "Uttaradit",
            "Amnat Charoen",
            "Bueng Kan",
            "Buriram",
            "Chaiyaphum",
            "Kalasin",
            "Khon Kaen",
            "Loei",
            "Maha Sarakham",
            "Mukdahan",
            "Nakhon Phanom",
            "Nakhon Ratchasima",
            "Nong Bua Lamphu",
            "Nong Khai",
            "Roi Et",
            "Sakon Nakhon",
            "Sisaket",
            "Surin",
            "Ubon Ratchathani",
            "Udon Thani",
            "Yasothon",
            "Ang Thong",
            "Ayutthaya",
            "Chainat",
            "Lop Buri",
            "Nakhon Nayok",
            "Nakhon Pathom",
            "Nonthaburi",
            "Pathum Thani",
            "Samut Prakan",
            "Samut Sakhon",
            "Samut Songkhram",
            "Saraburi",
            "Sing Buri",
            "Suphan Buri",
            "Chachoengsao",
            "Chanthaburi",
            "Chon Buri",
            "Prachin Buri",
            "Rayong",
            "Sa Kaeo",
            "Trat",
            "Kanchanaburi",
            "Nakhon Sawan",
            "Phetchabun",
            "Phichit",
            "Phitsanulok",
            "Kamphaeng Phet",
            "Sukhothai",
            "Tak",
            "Uthai Thani",
            "Ratchaburi",
            "Phetchaburi",
            "Prachuap Khiri Khan",
            "Chumphon",
            "Nakhon Si Thammarat",
            "Narathiwat",
            "Pattani",
            "Phang Nga",
            "Phatthalung",
            "Ranong",
            "Satun",
            "Songkhla",
            "Trang",
            "Yala",
        ],
        air_ticket_locations=[
            "Bangkok",
            "Chiang Mai",
            "Phuket",
            "Pattaya",
            "Krabi",
            "Koh Samui",
            "Chiang Rai",
            "Hat Yai",
            "Udon Thani",
            "Khon Kaen",
            "Ubon Ratchathani",
        ],
    ),
    "vietnam": CountryQueryConfig(
        country_label="Vietnam",
        district_locations=[
            "District 1 Ho Chi Minh City",
            "District 3 Ho Chi Minh City",
            "District 7 Ho Chi Minh City",
            "Phu Nhuan Ho Chi Minh City",
            "Tan Binh Ho Chi Minh City",
            "Binh Thanh Ho Chi Minh City",
            "Thu Duc Ho Chi Minh City",
            "Hoan Kiem Hanoi",
            "Ba Dinh Hanoi",
            "Dong Da Hanoi",
            "Cau Giay Hanoi",
            "Tay Ho Hanoi",
            "Hai Ba Trung Hanoi",
            "Thanh Xuan Hanoi",
            "Hai Chau Da Nang",
            "Son Tra Da Nang",
            "Ngu Hanh Son Da Nang",
            "Cam Chau Hoi An",
            "An Hoi Hoi An",
            "Loc Tho Nha Trang",
            "Duong Dong Phu Quoc",
        ],
        focus_locations=[
            "Ho Chi Minh City",
            "Hanoi",
            "Da Nang",
            "Hoi An",
            "Nha Trang",
            "Phu Quoc",
            "Hue",
            "Ha Long",
            "Da Lat",
            "Sapa",
            "Can Tho",
            "Hai Phong",
            "Quy Nhon",
            "Vung Tau",
        ],
        province_locations=[
            "An Giang",
            "Ba Ria Vung Tau",
            "Bac Giang",
            "Bac Kan",
            "Bac Lieu",
            "Bac Ninh",
            "Ben Tre",
            "Binh Dinh",
            "Binh Duong",
            "Binh Phuoc",
            "Binh Thuan",
            "Ca Mau",
            "Can Tho",
            "Cao Bang",
            "Da Nang",
            "Dak Lak",
            "Dak Nong",
            "Dien Bien",
            "Dong Nai",
            "Dong Thap",
            "Gia Lai",
            "Ha Giang",
            "Ha Nam",
            "Hanoi",
            "Ha Tinh",
            "Hai Duong",
            "Hai Phong",
            "Hau Giang",
            "Hoa Binh",
            "Hung Yen",
            "Khanh Hoa",
            "Kien Giang",
            "Kon Tum",
            "Lai Chau",
            "Lam Dong",
            "Lang Son",
            "Lao Cai",
            "Long An",
            "Nam Dinh",
            "Nghe An",
            "Ninh Binh",
            "Ninh Thuan",
            "Phu Tho",
            "Phu Yen",
            "Quang Binh",
            "Quang Nam",
            "Quang Ngai",
            "Quang Ninh",
            "Quang Tri",
            "Soc Trang",
            "Son La",
            "Tay Ninh",
            "Thai Binh",
            "Thai Nguyen",
            "Thanh Hoa",
            "Thua Thien Hue",
            "Tien Giang",
            "Ho Chi Minh City",
            "Tra Vinh",
            "Tuyen Quang",
            "Vinh Long",
            "Vinh Phuc",
            "Yen Bai",
        ],
        air_ticket_locations=[
            "Ho Chi Minh City",
            "Hanoi",
            "Da Nang",
            "Nha Trang",
            "Phu Quoc",
            "Hai Phong",
            "Can Tho",
            "Hue",
            "Da Lat",
        ],
    ),
    "indonesia": CountryQueryConfig(
        country_label="Indonesia",
        district_locations=[
            "Menteng Jakarta",
            "Kuningan Jakarta",
            "Kemang Jakarta",
            "Senayan Jakarta",
            "Sudirman Jakarta",
            "Thamrin Jakarta",
            "Kelapa Gading Jakarta",
            "Tebet Jakarta",
            "Pantai Indah Kapuk Jakarta",
            "Kuta Bali",
            "Legian Bali",
            "Seminyak Bali",
            "Canggu Bali",
            "Ubud Bali",
            "Sanur Bali",
            "Nusa Dua Bali",
            "Jimbaran Bali",
            "Denpasar Bali",
            "Malioboro Yogyakarta",
            "Dago Bandung",
            "Gubeng Surabaya",
        ],
        focus_locations=[
            "Jakarta",
            "Denpasar Bali",
            "Ubud Bali",
            "Kuta Bali",
            "Yogyakarta",
            "Bandung",
            "Surabaya",
            "Lombok",
            "Labuan Bajo",
            "Medan",
            "Makassar",
            "Semarang",
            "Malang",
            "Batam",
            "Manado",
            "Balikpapan",
        ],
        province_locations=[
            "Aceh",
            "North Sumatra",
            "West Sumatra",
            "Riau",
            "Jambi",
            "South Sumatra",
            "Bengkulu",
            "Lampung",
            "Bangka Belitung",
            "Riau Islands",
            "Jakarta",
            "West Java",
            "Central Java",
            "Yogyakarta",
            "East Java",
            "Banten",
            "Bali",
            "West Nusa Tenggara",
            "East Nusa Tenggara",
            "West Kalimantan",
            "Central Kalimantan",
            "South Kalimantan",
            "East Kalimantan",
            "North Kalimantan",
            "North Sulawesi",
            "Central Sulawesi",
            "South Sulawesi",
            "Southeast Sulawesi",
            "Gorontalo",
            "West Sulawesi",
            "Maluku",
            "North Maluku",
            "West Papua",
            "Papua",
        ],
        air_ticket_locations=[
            "Jakarta",
            "Denpasar Bali",
            "Surabaya",
            "Medan",
            "Makassar",
            "Yogyakarta",
            "Bandung",
            "Balikpapan",
            "Semarang",
            "Lombok",
            "Batam",
            "Manado",
        ],
    ),
    "philippines": CountryQueryConfig(
        country_label="Philippines",
        district_locations=[
            "Makati Metro Manila",
            "Bonifacio Global City Taguig",
            "Ortigas Pasig",
            "Quezon City Metro Manila",
            "Pasay Metro Manila",
            "Ermita Manila",
            "Malate Manila",
            "Alabang Muntinlupa",
            "Mandaluyong Metro Manila",
            "Cebu IT Park Cebu City",
            "Lapu-Lapu Mactan Cebu",
            "Station 1 Boracay",
            "Station 2 Boracay",
        ],
        focus_locations=[
            "Manila",
            "Cebu City",
            "Boracay",
            "Puerto Princesa Palawan",
            "El Nido Palawan",
            "Davao City",
            "Bohol",
            "Tagaytay",
            "Baguio",
            "Iloilo City",
            "Bacolod",
            "Siargao",
            "Dumaguete",
            "Cagayan de Oro",
            "Angeles Clark",
        ],
        province_locations=[
            "Metro Manila",
            "Cebu",
            "Bohol",
            "Palawan",
            "Iloilo",
            "Negros Occidental",
            "Negros Oriental",
            "Davao del Sur",
            "Aklan",
            "Pampanga",
            "Benguet",
            "Batangas",
            "Cavite",
            "Laguna",
            "Rizal",
            "Bulacan",
            "Pangasinan",
            "La Union",
            "Ilocos Norte",
            "Ilocos Sur",
            "Cagayan",
            "Isabela",
            "Nueva Ecija",
            "Tarlac",
            "Zambales",
            "Bataan",
            "Quezon",
            "Camarines Sur",
            "Albay",
            "Sorsogon",
            "Leyte",
            "Samar",
            "Capiz",
            "Antique",
            "Misamis Oriental",
            "Zamboanga del Sur",
            "South Cotabato",
            "Surigao del Norte",
            "Lanao del Norte",
        ],
        air_ticket_locations=[
            "Manila",
            "Cebu City",
            "Davao City",
            "Iloilo City",
            "Puerto Princesa Palawan",
            "Bacolod",
            "Cagayan de Oro",
            "Angeles Clark",
            "General Santos",
            "Zamboanga City",
            "Kalibo",
        ],
    ),
    "hongkong": CountryQueryConfig(
        country_label="Hong Kong",
        district_locations=[
            "Central",
            "Sheung Wan",
            "Admiralty",
            "Wan Chai",
            "Causeway Bay",
            "North Point",
            "Quarry Bay",
            "Tai Koo",
            "Aberdeen",
            "Wong Chuk Hang",
            "Tsim Sha Tsui",
            "Jordan",
            "Yau Ma Tei",
            "Mong Kok",
            "Prince Edward",
            "Sham Shui Po",
            "Cheung Sha Wan",
            "Kowloon City",
            "Ho Man Tin",
            "Kwun Tong",
            "Kowloon Bay",
            "San Po Kong",
            "Wong Tai Sin",
            "Kwai Chung",
            "Tsuen Wan",
            "Tsing Yi",
            "Sha Tin",
            "Tai Wai",
            "Tai Po",
            "Fanling",
            "Sheung Shui",
            "Yuen Long",
            "Tin Shui Wai",
            "Tuen Mun",
            "Tseung Kwan O",
            "Tung Chung",
            "Sai Kung",
        ],
        focus_locations=[
            "Central",
            "Tsim Sha Tsui",
            "Causeway Bay",
            "Mong Kok",
            "Wan Chai",
            "Sheung Wan",
            "Jordan",
            "Yau Ma Tei",
            "North Point",
            "Kwun Tong",
        ],
        province_locations=[
            "Hong Kong Island",
            "Kowloon",
            "New Territories",
            "Central and Western District",
            "Eastern District",
            "Southern District",
            "Yau Tsim Mong",
            "Sham Shui Po District",
            "Kowloon City District",
            "Wong Tai Sin District",
            "Kwun Tong District",
            "Sha Tin District",
            "Tsuen Wan District",
            "Tuen Mun District",
            "Yuen Long District",
            "Islands District",
        ],
        air_ticket_locations=[
            "Central",
            "Tsim Sha Tsui",
            "Mong Kok",
            "Causeway Bay",
            "Wan Chai",
            "Kowloon",
        ],
    ),
}


def build_queries(country: str) -> list[str]:
    cfg = COUNTRY_CONFIGS[country]
    queries: list[str] = []

    for location in cfg.district_locations:
        queries.append(f"travel agency in {location} {cfg.country_label}")

    for location in cfg.focus_locations:
        queries.append(f"travel agency in {location} {cfg.country_label}")
        queries.append(f"tour operator in {location} {cfg.country_label}")

    for location in cfg.air_ticket_locations:
        queries.append(f"airline ticket agency in {location} {cfg.country_label}")

    for location in cfg.province_locations:
        queries.append(f"travel agency in {location} {cfg.country_label}")

    return dedupe_preserve_order(queries)


def dedupe_preserve_order(items: list[str]) -> list[str]:
    seen: set[str] = set()
    output: list[str] = []
    for item in items:
        if item not in seen:
            seen.add(item)
            output.append(item)
    return output


def write_queries_file(path: Path, queries: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(queries) + "\n", encoding="utf-8")
